[package]
name = "runescape-simulator"
version = "0.1.0"
authors = ["Emily Eisenberg <xymostech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.3.0"
rand = "0.8.0"